CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    description LONGTEXT,
    short_description TEXT,
    price DECIMAL(10,2) NOT NULL,
    discount INT DEFAULT 0,
    rating DECIMAL(2,1) DEFAULT 0,
    stock INT DEFAULT 0,
    low_stock_threshold INT DEFAULT 0,
    min_order_quantity INT DEFAULT 1,
    max_order_quantity INT DEFAULT 100,
    category_id INT,
    sub_category_id INT,
    sub_sub_category_id INT,
    brand VARCHAR(100),
    sku VARCHAR(100),
    images JSON,
    sizes JSON,
    colors JSON,
    material VARCHAR(255),
    weight VARCHAR(50),
    dimensions VARCHAR(100),
    warranty VARCHAR(255),
    features JSON,
    tags JSON,
    status ENUM('active','inactive') DEFAULT 'active',
    is_featured TINYINT(1) DEFAULT 0,
    is_trending TINYINT(1) DEFAULT 0,
    is_bestseller TINYINT(1) DEFAULT 0,
    is_virtual TINYINT(1) DEFAULT 0,
    is_downloadable TINYINT(1) DEFAULT 0,
    download_link VARCHAR(500),
    shipping_class VARCHAR(50) DEFAULT 'Standard',
    tax_class VARCHAR(50) DEFAULT '0',
    shipping_cost DECIMAL(10,2) DEFAULT 0,
    free_shipping TINYINT(1) DEFAULT 0,
    seo_title VARCHAR(255),
    seo_description TEXT,
    meta_keywords TEXT,
    return_policy TEXT,
    video VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (sub_category_id) REFERENCES sub_categories(id),
    FOREIGN KEY (sub_sub_category_id) REFERENCES sub_sub_categories(id)
);